export const chapters = [
    {
        slug: "01-first-principles",
        part: "第一部｜最小閉環",
        title: "從 LLM 到 Agent",
        description: "拆開 LLM、Agent 與 coding agent，親手建立不可再刪的 model → tool → result 閉環。",
        file: "01-first-principles.html",
        minutes: 14,
    },
    {
        slug: "02-messages-provider",
        part: "第一部｜最小閉環",
        title: "訊息、Transcript 與 Provider Adapter",
        description: "理解無狀態模型如何藉由 transcript 延續工作，以及 provider wire format 為何不能直接進入核心。",
        file: "02-messages-provider.html",
        minutes: 18,
    },
    {
        slug: "03-tools",
        part: "第二部｜能力邊界",
        title: "Tool 是 Agent 的手",
        description: "設計小而深的 Tool 介面、runtime validation、錯誤語意與可安全擴充的 plugin bundle。",
        file: "03-tools.html",
        minutes: 20,
    },
    {
        slug: "04-context-skills",
        part: "第二部｜能力邊界",
        title: "Context、AGENTS.md 與 Skills",
        description: "把專案規則與領域知識放入正確層級，使用 progressive loading 控制 context 成本。",
        file: "04-context-skills.html",
        minutes: 15,
    },
    {
        slug: "05-durable-session",
        part: "第三部｜可靠執行",
        title: "Durable Session：先記 Intent，再做 Effect",
        description: "用 transactional JSONL 保存接受的工作、model attempt 與 tool intent，讓 crash 後仍可解釋。",
        file: "05-durable-session.html",
        minutes: 26,
    },
    {
        slug: "06-recovery",
        part: "第三部｜可靠執行",
        title: "Reducer、Planner 與 Recovery",
        description: "以 pure reducer 重建狀態，再由 planner 區分 retry、replay、interrupted 與 blocked。",
        file: "06-recovery.html",
        minutes: 25,
    },
    {
        slug: "07-cancel-compact",
        part: "第三部｜可靠執行",
        title: "Cancellation 與 Durable Compaction",
        description: "處理 abort race、合法 transcript，以及 active-context cut 與 durable source partition 的差異。",
        file: "07-cancel-compact.html",
        minutes: 22,
    },
    {
        slug: "08-test-observe-secure",
        part: "第四部｜走向 Production",
        title: "測試、Observability 與安全邊界",
        description: "用 deterministic fixtures 與 run events 提升成功率，同時劃清 MCP、sandbox 與多租戶責任。",
        file: "08-test-observe-secure.html",
        minutes: 24,
    },
];

export const planned = [
    "TypeScript 實作深讀：從 CLI 到 Agent loop",
    "Go 實作深讀：context、process group 與 terminal",
    "Python 實作深讀：同步 I/O 與 cancellation",
    "Rust 實作深讀：ownership、blocking transport 與 CJK terminal",
    "企業調查 Agent：Sentry、logs、code search 與 evidence packet",
];
